<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>SoM GenAI Learning Interests & Readiness Survey</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    /* Code Generated by Sidekick is for learning and experimentation purposes only. */
    :root {
      --brand: #0f62fe;
      --brand-dark: #0043ce;
      --bg: #fafafa;
      --border: #e0e0e0;
      --text: #161616;
      --muted: #6f6f6f;
      --danger: #da1e28;
      --success: #198038;
    }
    body {
      font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
      margin: 0; padding: 0; background: var(--bg); color: var(--text);
    }
    .container {
      max-width: 900px; margin: 24px auto; padding: 24px; background: #fff;
      border: 1px solid var(--border); border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.04);
    }
    h1 { margin-top: 0; font-size: 1.6rem; }
    .intro { color: var(--muted); margin-bottom: 16px; }
    .section { border-top: 1px solid var(--border); padding-top: 16px; margin-top: 16px; }
    .q { margin: 16px 0; }
    .q label.qt { display: block; font-weight: 600; margin-bottom: 8px; }
    .help { color: var(--muted); font-size: 0.9rem; margin-top: 4px; }
    .row { display: flex; gap: 12px; flex-wrap: wrap; }
    .chip { display: inline-flex; align-items: center; gap: 8px; margin: 4px 8px 4px 0; }
    input[type="text"], input[type="email"], select, textarea {
      width: 100%; padding: 10px 12px; border: 1px solid var(--border); border-radius: 8px; font-size: 1rem;
    }
    textarea { min-height: 100px; }
    .choices { display: flex; flex-direction: column; gap: 8px; }
    .inline { display: inline-block; margin-right: 16px; }
    .actions { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 16px; }
    button {
      background: var(--brand); color: white; border: 0; padding: 10px 16px; border-radius: 8px; cursor: pointer;
    }
    button.secondary { background: #e8f0fe; color: #0f62fe; }
    button[disabled] { opacity: 0.5; cursor: not-allowed; }
    .msg { margin-top: 12px; font-size: 0.95rem; }
    .msg.success { color: var(--success); }
    .msg.error { color: var(--danger); }
    .hr { height: 1px; background: var(--border); margin: 16px 0; }
    .required { color: var(--danger); margin-left: 4px; }
    .footer-note { color: var(--muted); font-size: 0.85rem; margin-top: 24px; }
  </style>
</head>
<body>
<div class="container">
  <h1>SoM GenAI Learning Interests & Readiness Survey</h1>
  <p class="intro">
    This brief survey (3–5 minutes) helps tailor GenAI learning to your needs. We’ll aggregate results to guide planning; individual responses
    won’t be shared outside the planning team.
  </p>

  <!-- Consent -->
  <div class="q">
    <label class="qt">Consent to proceed?<span class="required">*</span></label>
    <div class="choices" id="consent">
      <label class="inline"><input type="radio" name="consent" value="Yes" required> Yes, continue</label>
      <label class="inline"><input type="radio" name="consent" value="No"> No, exit survey</label>
    </div>
  </div>
  <div id="consent-exit" class="msg" style="display:none;">Thanks for your time.</div>
  <div class="hr"></div>

  <!-- Q1 Comfort -->
  <div class="q">
    <label class="qt">Q1. How comfortable are you with using AI?<span class="required">*</span></label>
    <select id="comfort" required>
      <option value="">Select one</option>
      <option value="1 – New to AI (need basics)">1 – New to AI (need basics)</option>
      <option value="2 – Some exposure">2 – Some exposure</option>
      <option value="3 – Comfortable with common tools">3 – Comfortable with common tools</option>
      <option value="4 – Confident (use AI regularly)">4 – Confident (use AI regularly)</option>
      <option value="5 – Advanced (build/evaluate AI solutions)">5 – Advanced (build/evaluate AI solutions)</option>
    </select>
  </div>

  <!-- Q2 Tools -->
  <div class="q">
    <label class="qt">Q2. Which AI tools have you used? Select all that apply.<span class="required">*</span></label>
    <div class="choices" id="tools">
      <label><input type="checkbox" value="ChatGPT / GPT-4 or later"> ChatGPT / GPT-4 or later</label>
      <label><input type="checkbox" value="Microsoft Copilot (M365/GitHub/Windows)"> Microsoft Copilot (M365/GitHub/Windows)</label>
      <label><input type="checkbox" value="Google Gemini"> Google Gemini</label>
      <label><input type="checkbox" value="Claude (Anthropic)"> Claude (Anthropic)</label>
      <label><input type="checkbox" value="Perplexity"> Perplexity</label>
      <label><input type="checkbox" value="Midjourney / Stable Diffusion / DALL·E"> Midjourney / Stable Diffusion / DALL·E</label>
      <label><input type="checkbox" value="Azure OpenAI services"> Azure OpenAI services</label>
      <label><input type="checkbox" value="Amazon Bedrock / CodeWhisperer"> Amazon Bedrock / CodeWhisperer</label>
      <label><input type="checkbox" value="Databricks / MLflow / AutoML"> Databricks / MLflow / AutoML</label>
      <label><input type="checkbox" value="Other"> Other (please specify)</label>
      <label><input type="checkbox" value="None yet" id="tools-none"> None yet</label>
    </div>
    <div id="tools-other-wrap" style="display:none; margin-top:8px;">
      <input type="text" id="tools-other" placeholder="Please specify other tool(s)" />
    </div>
  </div>

  <!-- Q3 Frequency -->
  <div class="q" id="freq-wrap">
    <label class="qt">Q3. How often do you use AI tools in your work?</label>
    <select id="frequency">
      <option value="">Select one</option>
      <option>Daily</option>
      <option>Weekly</option>
      <option>Monthly</option>
      <option>Rarely</option>
      <option>Never</option>
    </select>
    <div class="help">Shown only if you’ve used any tools.</div>
  </div>

  <!-- Q4 Role -->
  <div class="q">
    <label class="qt">Q4. What is your primary role?<span class="required">*</span></label>
    <select id="role" required>
      <option value="">Select one</option>
      <option>Developer/Engineer</option>
      <option>Business Analyst (BA)</option>
      <option>Tester/QA</option>
      <option>Data/ML Engineer or Scientist</option>
      <option>Product/Project Manager</option>
      <option>Architecture</option>
      <option>Design/UX</option>
      <option>Operations/Support</option>
      <option>Leadership/People Manager</option>
      <option>Other</option>
    </select>
    <div id="role-other-wrap" style="display:none; margin-top:8px;">
      <input type="text" id="role-other" placeholder="Please specify your role" />
    </div>
  </div>

  <!-- Q5 Learning Interests -->
  <div class="q">
    <label class="qt">Q5. What do you want to learn more about regarding AI? Select up to 5.<span class="required">*</span></label>
    <div class="choices" id="interests">
      <label><input type="checkbox" value="Foundations: prompts, safety, limitations"> Foundations: prompts, safety, limitations</label>
      <label><input type="checkbox" value="Productivity: summarization, drafting, research"> Productivity: summarization, drafting, research</label>
      <label><input type="checkbox" value="Prompt engineering for high-quality outputs"> Prompt engineering for high-quality outputs</label>
      <label><input type="checkbox" value="Using GenAI in Microsoft 365/Copilot"> Using GenAI in Microsoft 365/Copilot</label>
      <label><input type="checkbox" value="Using GenAI for coding (GitHub Copilot)"> Using GenAI for coding (GitHub Copilot)</label>
      <label><input type="checkbox" value="Data privacy, security, and responsible AI"> Data privacy, security, and responsible AI</label>
      <label><input type="checkbox" value="Evaluation of AI outputs (quality/guardrails)"> Evaluation of AI outputs (quality/guardrails)</label>
      <label><input type="checkbox" value="Building apps with APIs (Azure OpenAI, Gemini, Bedrock)"> Building apps with APIs (Azure OpenAI, Gemini, Bedrock)</label>
      <label><input type="checkbox" value="RAG (retrieval augmented generation)"> RAG (retrieval augmented generation)</label>
      <label><input type="checkbox" value="Fine-tuning and embeddings basics"> Fine-tuning and embeddings basics</label>
      <label><input type="checkbox" value="Model selection and cost/performance trade-offs"> Model selection and cost/performance trade-offs</label>
      <label><input type="checkbox" value="LLM ops: monitoring, telemetry, and cost control"> LLM ops: monitoring, telemetry, and cost control</label>
      <label><input type="checkbox" value="Testing AI systems (quality, bias, hallucinations)"> Testing AI systems (quality, bias, hallucinations)</label>
      <label><input type="checkbox" value="Integrating AI in SDLC/DevOps"> Integrating AI in SDLC/DevOps</label>
      <label><input type="checkbox" value="Domain-specific use cases"> Domain-specific use cases (please specify)</label>
    </div>
    <div id="interests-other-wrap" style="display:none; margin-top:8px;">
      <input type="text" id="interests-other" placeholder="Please specify domain or topic" />
    </div>
    <div class="help" id="interest-limit-msg">You can select up to 5.</div>
  </div>

  <!-- Q6 Implementation Ideas -->
  <div class="q">
    <label class="qt">Q6. Do you have any ideas on how to implement AI in your role already?<span class="required">*</span></label>
    <div class="choices" id="idea-flag">
      <label class="inline"><input type="radio" name="idea" value="Yes" required> Yes</label>
      <label class="inline"><input type="radio" name="idea" value="Not yet" required> Not yet</label>
      <label class="inline"><input type="radio" name="idea" value="Prefer to discuss live" required> Prefer to discuss live</label>
    </div>
    <div id="idea-text-wrap" style="display:none; margin-top:8px;">
      <label for="idea-text" class="qt">Please describe your idea briefly (what problem, where in workflow, expected benefit).</label>
      <textarea id="idea-text" maxlength="800" placeholder="Example: Use AI to auto-summarize test results to reduce reporting time by 30%..."></textarea>
    </div>
  </div>

  <!-- Q7 Session Formats -->
  <div class="q">
    <label class="qt">Q7. Which session formats would be most helpful?<span class="required">*</span></label>
    <div class="choices" id="formats">
      <label><input type="checkbox" value="Live demo + Q&A (60–90 min)"> Live demo + Q&A (60–90 min)</label>
      <label><input type="checkbox" value="Hands-on lab with guided exercises"> Hands-on lab with guided exercises</label>
      <label><input type="checkbox" value="Role-based breakout"> Role-based breakout</label>
      <label><input type="checkbox" value="Office hours / coaching"> Office hours / coaching</label>
      <label><input type="checkbox" value="Self-paced materials and quick reference guides"> Self-paced materials and quick reference guides</label>
      <label><input type="checkbox" value="Show-and-tell of internal use cases"> Show-and-tell of internal use cases</label>
    </div>
  </div>

  <!-- Q8 Timing -->
  <div class="q">
    <label class="qt">Q8. What times work best for live sessions?</label>
    <div class="choices" id="timing">
      <label><input type="checkbox" value="Mornings"> Mornings</label>
      <label><input type="checkbox" value="Midday"> Midday</label>
      <label><input type="checkbox" value="Afternoons"> Afternoons</label>
      <label><input type="checkbox" value="Evenings"> Evenings</label>
    </div>
    <div style="margin-top:8px;">
      <input type="text" id="timezone" placeholder="Time zone (optional)" />
    </div>
  </div>

  <!-- Q9 Follow-up -->
  <div class="q">
    <label class="qt">Q9. Are you open to a short follow-up to explore your needs or pilot ideas?</label>
    <select id="followup">
      <option value="">Select one</option>
      <option>Yes</option>
      <option>Maybe</option>
      <option>No</option>
    </select>
    <div id="contact-wrap" style="display:none; margin-top:8px;">
      <div class="row">
        <input type="text" id="name" placeholder="Name (optional)" />
        <input type="email" id="email" placeholder="Email (optional)" />
      </div>
      <div class="help">Email is validated if provided.</div>
    </div>
  </div>

  <!-- Actions -->
  <div class="actions">
    <button id="submit">Submit response</button>
    <button class="secondary" id="download-xlsx">Download Excel</button>
    <button class="secondary" id="download-csv">Download CSV</button>
    <!-- Optional: enable central collection by pointing to a webhook -->
    <!-- <button class="secondary" id="send-webhook">Send to Webhook</button> -->
  </div>
  <div id="status" class="msg"></div>

  <p class="footer-note">
    Tip: You can download Excel/CSV anytime. Data persists in this page until refresh/close. For centralized storage, connect a webhook (instructions below).
  </p>
</div>

<!-- XLSX library (SheetJS community build) -->
<script src="https://cdn.jsdelivr.net/npm/xlsx@0.20.0/dist/xlsx.full.min.js"></script>

<script>
  // Code Generated by Sidekick is for learning and experimentation purposes only.

  // In-memory store
  const responses = [];

  // Helpers
  const qs = (sel) => document.querySelector(sel);
  const qsa = (sel) => Array.from(document.querySelectorAll(sel));
  const getCheckedValues = (containerSel) =>
    qsa(containerSel + ' input[type="checkbox"]:checked').map(c => c.value);

  // Branching: Consent
  qsa('input[name="consent"]').forEach(r => {
    r.addEventListener('change', () => {
      const exit = qs('#consent-exit');
      if (r.value === 'No' && r.checked) {
        exit.style.display = 'block';
        qs('#submit').disabled = true;
      } else {
        exit.style.display = 'none';
        qs('#submit').disabled = false;
      }
    });
  });

  // Tools: show/hide "Other" and control "None yet"
  const toolsContainer = qs('#tools');
  const toolsOtherWrap = qs('#tools-other-wrap');
  const toolsOther = qs('#tools-other');
  const toolsNone = qs('#tools-none');
  toolsContainer.addEventListener('change', () => {
    const values = getCheckedValues('#tools');
    toolsOtherWrap.style.display = values.includes('Other') ? 'block' : 'none';
    if (values.includes('None yet')) {
      // Uncheck all others
      qsa('#tools input[type="checkbox"]').forEach(cb => {
        if (cb.value !== 'None yet') cb.checked = false;
      });
      toolsOtherWrap.style.display = 'none';
    } else {
      // Ensure None yet unchecked if others chosen
      if (toolsNone.checked) toolsNone.checked = false;
    }
    // Show/hide frequency
    qs('#freq-wrap').style.display = values.includes('None yet') ? 'none' : 'block';
  });

  // Role: show/hide "Other"
  const roleSelect = qs('#role');
  const roleOtherWrap = qs('#role-other-wrap');
  const roleOther = qs('#role-other');
  roleSelect.addEventListener('change', () => {
    roleOtherWrap.style.display = roleSelect.value === 'Other' ? 'block' : 'none';
  });

  // Interests: max 5 and show/hide other text
  const interests = qsa('#interests input[type="checkbox"]');
  const interestsOtherWrap = qs('#interests-other-wrap');
  const interestsOther = qs('#interests-other');
  interests.forEach(cb => {
    cb.addEventListener('change', () => {
      const selected = interests.filter(i => i.checked);
      const otherChecked = selected.some(i => i.value === 'Domain-specific use cases');
      interestsOtherWrap.style.display = otherChecked ? 'block' : 'none';
      if (selected.length > 5) {
        cb.checked = false;
        qs('#interest-limit-msg').textContent = 'Limit reached: You can select up to 5.';
        qs('#interest-limit-msg').style.color = '#da1e28';
        setTimeout(() => {
          qs('#interest-limit-msg').textContent = 'You can select up to 5.';
          qs('#interest-limit-msg').style.color = '';
        }, 2000);
      }
    });
  });

  // Implementation ideas: conditional text
  qsa('input[name="idea"]').forEach(r => {
    r.addEventListener('change', () => {
      qs('#idea-text-wrap').style.display = r.value === 'Yes' ? 'block' : 'none';
    });
  });

  // Follow-up: conditional contact fields
  const followup = qs('#followup');
  const contactWrap = qs('#contact-wrap');
  followup.addEventListener('change', () => {
    contactWrap.style.display = (followup.value === 'Yes' || followup.value === 'Maybe') ? 'block' : 'none';
  });

  // Validate required selections
  function validateRequired() {
    const status = qs('#status');
    // consent
    const consent = qsa('input[name="consent"]:checked')[0]?.value || '';
    if (!consent || consent === 'No') {
      status.className = 'msg error';
      status.textContent = 'Please provide consent to proceed.';
      return false;
    }
    // comfort
    if (!qs('#comfort').value) {
      status.className = 'msg error';
      status.textContent = 'Please select your comfort level.';
      return false;
    }
    // tools: require at least one checkbox (including None yet)
    if (getCheckedValues('#tools').length === 0) {
      status.className = 'msg error';
      status.textContent = 'Please select at least one tool option.';
      return false;
    }
    // role
    if (!roleSelect.value) {
      status.className = 'msg error';
      status.textContent = 'Please select your role.';
      return false;
    }
    // learning interests: at least 1 up to 5
    const li = getCheckedValues('#interests');
    if (li.length === 0) {
      status.className = 'msg error';
      status.textContent = 'Please select at least one learning interest.';
      return false;
    }
    if (li.length > 5) {
      status.className = 'msg error';
      status.textContent = 'You can select up to 5 learning interests.';
      return false;
    }
    // idea text required if Yes
    const ideaFlag = qsa('input[name="idea"]:checked')[0]?.value || '';
    if (!ideaFlag) {
      status.className = 'msg error';
      status.textContent = 'Please select an option for implementation ideas.';
      return false;
    }
    if (ideaFlag === 'Yes' && !qs('#idea-text').value.trim()) {
      status.className = 'msg error';
      status.textContent = 'Please describe your implementation idea.';
      return false;
    }
    // contact email validation if provided
    const email = qs('#email').value.trim();
    if (email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      status.className = 'msg error';
      status.textContent = 'Please enter a valid email address.';
      return false;
    }
    status.textContent = '';
    return true;
  }

  function collectResponse() {
    const consent = qsa('input[name="consent"]:checked')[0]?.value || '';
    const comfort = qs('#comfort').value;
    const tools = getCheckedValues('#tools');
    const toolsOtherVal = tools.includes('Other') ? (qs('#tools-other').value.trim() || '') : '';
    const frequency = qs('#freq-wrap').style.display === 'none' ? '' : (qs('#frequency').value || '');

    const role = qs('#role').value;
    const roleOtherVal = role === 'Other' ? (qs('#role-other').value.trim() || '') : '';

    const interestsVals = getCheckedValues('#interests');
    const interestsOtherVal = interestsVals.includes('Domain-specific use cases') ? (qs('#interests-other').value.trim() || '') : '';

    const ideaFlag = qsa('input[name="idea"]:checked')[0]?.value || '';
    const ideaText = ideaFlag === 'Yes' ? (qs('#idea-text').value.trim() || '') : '';

    const formats = getCheckedValues('#formats');
    const timing = getCheckedValues('#timing');
    const timezone = qs('#timezone').value.trim();

    const followup = qs('#followup').value || '';
    const name = qs('#name').value.trim();
    const email = qs('#email').value.trim();

    return {
      timestamp: new Date().toISOString(),
      consent,
      comfort,
      tools_used: tools.join('; '),
      tools_used_other: toolsOtherVal,
      tools_frequency: frequency,
      role,
      role_other: roleOtherVal,
      learning_interests: interestsVals.join('; '),
      learning_interests_other: interestsOtherVal,
      implementation_idea_flag: ideaFlag,
      implementation_idea_text: ideaText,
      session_formats: formats.join('; '),
      timing_preferences: timing.join('; '),
      timezone,
      followup_optin: followup,
      name,
      email
    };
  }

  function addResponse(resp) {
    responses.push(resp);
  }

  function resetForm() {
    // Reset all inputs; preserve consent area to allow multiple submissions
    qsa('input, select, textarea').forEach(el => {
      if (el.type === 'radio' || el.type === 'checkbox') el.checked = false;
      if (el.tagName === 'SELECT') el.value = '';
      if (el.tagName === 'TEXTAREA' || el.type === 'text' || el.type === 'email') el.value = '';
    });
    // Restore conditional UI
    qs('#freq-wrap').style.display = 'block';
    qs('#tools-other-wrap').style.display = 'none';
    qs('#role-other-wrap').style.display = 'none';
    qs('#interests-other-wrap').style.display = 'none';
    qs('#idea-text-wrap').style.display = 'none';
    qs('#contact-wrap').style.display = 'none';
    // Reset consent to allow new participant choice
    qsa('input[name="consent"]').forEach(r => r.checked = false);
  }

  function toWorksheetData() {
    const headers = [
      'timestamp','consent','comfort','tools_used','tools_used_other','tools_frequency',
      'role','role_other','learning_interests','learning_interests_other','implementation_idea_flag',
      'implementation_idea_text','session_formats','timing_preferences','timezone','followup_optin',
      'name','email'
    ];
    const data = [headers];
    responses.forEach(r => {
      data.push(headers.map(h => r[h] ?? ''));
    });
    return data;
  }

  function downloadCSV() {
    const rows = toWorksheetData();
    const csv = rows.map(r => r.map(v => {
      // Escape quotes and commas
      const s = String(v ?? '');
      if (/[",\n]/.test(s)) return `"${s.replace(/"/g,'""')}"`;
      return s;
    }).join(',')).join('\n');
    const blob = new Blob([csv], {type: 'text/csv;charset=utf-8;'});
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'SoM_GenAI_Survey.csv';
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function downloadXLSX() {
    const data = toWorksheetData();
    const ws = XLSX.utils.aoa_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Responses');
    XLSX.writeFile(wb, 'SoM_GenAI_Survey.xlsx');
  }

  // Event handlers
  qs('#submit').addEventListener('click', () => {
    const status = qs('#status');
    status.className = 'msg';
    status.textContent = '';
    if (!validateRequired()) return;

    const resp = collectResponse();
    addResponse(resp);
    status.className = 'msg success';
    status.textContent = 'Response recorded. You can submit another or download Excel/CSV.';
    resetForm();
  });

  qs('#download-csv').addEventListener('click', () => {
    if (responses.length === 0) {
      qs('#status').className = 'msg error';
      qs('#status').textContent = 'No responses yet to download.';
      return;
    }
    downloadCSV();
  });

  qs('#download-xlsx').addEventListener('click', () => {
    if (responses.length === 0) {
      qs('#status').className = 'msg error';
      qs('#status').textContent = 'No responses yet to download.';
      return;
    }
    downloadXLSX();
  });

  // Optional webhook sender (commented UI above)
  async function sendToWebhook(endpointUrl) {
    const status = qs('#status');
    if (responses.length === 0) {
      status.className = 'msg error';
      status.textContent = 'No responses to send.';
      return;
    }
    try {
      const res = await fetch(endpointUrl, {
        method: 'POST',
        headers: {'Content-Type':'application/json'},
        body: JSON.stringify({ survey: 'SoM GenAI', responses })
      });
      if (!res.ok) throw new Error('Failed to send: ' + res.status);
      status.className = 'msg success';
      status.textContent = 'Responses sent to webhook successfully.';
    } catch (e) {
      status.className = 'msg error';
      status.textContent = 'Webhook error: ' + e.message;
    }
  }

  // Expose webhook function if needed:
  window.SoMSurvey = { sendToWebhook };
</script>
</body>
</html>
