# Code Generated by Sidekick is for learning and experimentation purposes only.
import streamlit as st
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
from pathlib import Path
import csv
import io

# -------------------------
# App configuration & styles
# -------------------------
st.set_page_config(page_title="SoM AI First Learning Interests & Readiness Survey", page_icon="📝", layout="centered")

BRAND_CSS = """
<style>
:root {
  --brand: #0f62fe;
  --brand-dark: #0043ce;
  --bg: #fafafa;
  --border: #e0e0e0;
  --text: #161616;
  --muted: #6f6f6f;
  --danger: #da1e28;
  --success: #198038;
}
html, body, [class*="css"]  {
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
}
.container-like {
  max-width: 900px;
  margin: 0 auto;
  background: #fff;
  padding: 16px 20px;
  border: 1px solid var(--border);
  border-radius: 12px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.04);
}
.intro { color: var(--muted); margin-bottom: 12px; }
.hr { height: 1px; background: var(--border); margin: 16px 0; }
.required { color: var(--danger); margin-left: 4px; }
.success { color: var(--success); font-weight: 600; }
.error { color: var(--danger); font-weight: 600; }
.help { color: var(--muted); font-size: 0.9rem; }
</style>
"""
st.markdown(BRAND_CSS, unsafe_allow_html=True)

# -------------------------
# Constants
# -------------------------
CSV_PATH = Path("SoM_GenAI_Survey.csv")

TOOLS_OPTIONS = [
    "ChatGPT",
    "GPS Sidekick",
    "Microsoft Copilot",
    "Google Gemini",
    "Claude",
    "Other (please specify)",
    "None yet",
]

ROLE_OPTIONS = [
    "Developer",
    "Business Analyst",
    "Tester/QA",
    "Project Manager",
    "Design/UX",
    "Leadership/People Manager",
    "Organizational Change Management",
    "Other",
]

FORMATS_OPTIONS = [
    "Live demo + Q&A (60–90 min)",
    "Hands-on lab with guided exercises",
    "Role-based breakout",
    "Office hours / coaching",
    "Self-paced materials and quick reference guides",
    "Show-and-tell of internal use cases",
]

COMFORT_OPTIONS = [
    "1 – New to AI (need basics)",
    "2 – Some exposure",
    "3 – Comfortable with common tools",
    "4 – Confident (use AI regularly)",
    "5 – Advanced (build/evaluate AI solutions)",
]

FREQ_OPTIONS = ["Daily", "Weekly", "Monthly", "Rarely", "Never"]

# Curated choices to replace free-response for Q5 (condensed, fast to answer)
LEARNING_INTERESTS_OPTIONS = [
    "GenAI for everyday work (Copilot + ChatGPT/Sidekick)",
    "Advanced prompting for accuracy and speed",
    "Research and analysis at consulting speed",
    "Technical build patterns and coding: RAG, APIs, and automations",
    "AI for testing/QA and documentation",
    "Responsible AI, security, and data handling",
    "Other (please specify)",
]

# Output schema columns (kept for compatibility; removed fields will be saved as blanks)
COLUMNS = [
    "comfort","tools_used","tools_used_other","tools_frequency",
    "role","role_other","learning_interests","learning_interests_other","implementation_idea_flag",
    "implementation_idea_text","session_formats", "timestamp"
]

# -------------------------
# Utilities: CSV append + load
# -------------------------
def append_row_to_csv(row: dict):
    record = {c: row.get(c, "") for c in COLUMNS}
    is_new = not CSV_PATH.exists() or CSV_PATH.stat().st_size == 0
    with CSV_PATH.open("a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=COLUMNS)
        if is_new:
            w.writeheader()
        w.writerow(record)

def df_current() -> pd.DataFrame:
    if CSV_PATH.exists() and CSV_PATH.stat().st_size > 0:
        try:
            return pd.read_csv(CSV_PATH)
        except Exception:
            return pd.DataFrame(columns=COLUMNS)
    return pd.DataFrame(columns=COLUMNS)

# -------------------------
# UI
# -------------------------
st.markdown('<div class="container-like">', unsafe_allow_html=True)
st.title("SoM GenAI Learning Interests & Readiness Survey")
st.markdown(
    '<p class="intro">Take a quick (3–5 minute) survey to help us design GenAI learning that’s most useful for you!</p>',
    unsafe_allow_html=True,
)

with st.form("survey_form", clear_on_submit=True):
    # Consent
    consent = st.radio("Consent to proceed?*", options=["Yes, continue", "No, exit survey"], horizontal=True, index=0)

    st.markdown('<div class="hr"></div>', unsafe_allow_html=True)
    
    # Q1 Comfort
    comfort = st.selectbox("Q1. How comfortable are you with using AI?*", options=["Select one"] + COMFORT_OPTIONS)

    # Q2 Tools
    tools = st.multiselect("Q2. Which AI tools have you used? Select all that apply.*", TOOLS_OPTIONS)
    tools_other = ""
    if "None yet" in tools and len(tools) > 1:
        tools = ["None yet"]
    if "Other (please specify)" in tools:
        tools_other = st.text_input("Please specify other tool(s)")

    # Q3 Frequency (only if used tools)
    frequency = ""
    if "None yet" not in tools:
        frequency = st.selectbox("Q3. How often do you use AI tools in your work?", options=["Select one"] + FREQ_OPTIONS)

    # Q4 Role (show "Other" text input only when "Other" is selected)
    role = st.selectbox(
        "Q4. What is your primary role?*",
        options=["Select one"] + ROLE_OPTIONS,
        key="role_select",
    )
    role_other = ""
    if role == "Other":
        role_other = st.text_input(
            "If not listed, please specify your role",
            key="role_other_text",
            placeholder="e.g., Data Engineer, Scrum Master",
        )

    # Q5 Interests — condensed (multi-select with optional short 'Other')
    # Preserves your question text, replaces free text with curated options
    learning = st.multiselect(
        "Q5. What do you want to learn more about regarding AI? Select up to 3 topics.*",
        options=LEARNING_INTERESTS_OPTIONS,
    )
    learning_other = ""
    # Enforce cap to 3 selections for speed/signal (soft-gate in validation)
    if "Other (please specify)" in learning:
        learning_other = st.text_input("Other interest (short)")

    # Q6 Implementation ideas — show text area only when "Yes" is selected
    idea_flag = st.radio(
        "Q6. Do you have any ideas on how to implement AI in your role already?*",
        ["Yes", "Not yet"],
        horizontal=True,
        key="idea_flag",
    )
    idea_text = ""
    if idea_flag == "Yes":
        st.write("If yes, please describe your idea briefly (what problem, where in workflow, expected benefit).")
        idea_text = st.text_area(
            label="",
            key="idea_text",
            max_chars=400,
            placeholder="Example: Use AI to auto-summarize test results to reduce reporting time by 30%...",
            height=100,
        )

    # Q7 Session formats
    formats = st.multiselect("Q7. Which session formats would be most helpful?*", FORMATS_OPTIONS)

    # Submit button
    submitted = st.form_submit_button("Submit response")

# -------------------------
# Validation & Submission
# -------------------------
status_area = st.empty()

def required_field_checks():
    # Consent
    if consent != "Yes, continue":
        return False, "Please provide consent to proceed."
    if comfort == "Select one":
        return False, "Please select your comfort level."
    if len(tools) == 0:
        return False, "Please select at least one tool option."
    if role == "Select one":
        return False, "Please select your role."
    if not learning:
        return False, "Please select at least one topic for Q5."
    if len(learning) > 3:
        return False, "Please select up to 3 topics for Q5."
    if "Other (please specify)" in learning and not (learning_other or "").strip():
        return False, "Please provide a short topic for Q5 'Other'."
    if idea_flag == "Yes" and not (idea_text or "").strip():
        return False, "Please describe your implementation idea."
    return True, ""

if submitted:
    ok, msg = required_field_checks()
    if not ok:
        status_area.markdown(f'<p class="error">{msg}</p>', unsafe_allow_html=True)
    else:
        # Map condensed Q5 selections to schema fields
        selected_topics = [t for t in learning if t != "Other (please specify)"]
        row = {
            "comfort": comfort,
            "tools_used": "; ".join(tools),
            "tools_used_other": (tools_other or "").strip() if "Other (please specify)" in tools else "",
            "tools_frequency": "" if "None yet" in tools else (frequency if frequency != "Select one" else ""),
            "role": role,
            "role_other": (role_other or "").strip() if role == "Other" else "",
            "learning_interests": "; ".join(selected_topics),
            "learning_interests_other": (learning_other or "").strip() if "Other (please specify)" in learning else "",
            "implementation_idea_flag": idea_flag,
            "implementation_idea_text": (idea_text or "").strip() if idea_flag == "Yes" else "",
            "session_formats": "; ".join(formats),
            "timestamp": datetime.now(ZoneInfo("America/Detroit")).strftime("%Y-%m-%d %H:%M:%S"),
        }
        try:
            append_row_to_csv(row)
            status_area.markdown('<p class="success">Response recorded. Thank you! </p>', unsafe_allow_html=True)
        except Exception as e:
            status_area.markdown(f'<p class="error">Could not save your response: {e}</p>', unsafe_allow_html=True)

# -------------------------
# Downloads and live view
# -------------------------
st.markdown('<div class="hr"></div>', unsafe_allow_html=True)
st.subheader("Responses")

current_df = df_current()
st.caption("Live responses (from CSV):")
st.dataframe(current_df, use_container_width=True, hide_index=True)

# Download latest CSV
csv_buf = io.StringIO()
current_df.to_csv(csv_buf, index=False)
st.download_button(
    "Download CSV",
    data=csv_buf.getvalue(),
    file_name=CSV_PATH.name,
    mime="text/csv",
)

st.markdown("</div>", unsafe_allow_html=True)
